// <auto-generated />
namespace MRM.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LocalFisrt_310517 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LocalFisrt_310517));
        
        string IMigrationMetadata.Id
        {
            get { return "201705311147380_LocalFisrt_310517"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
